### ISSUE TITLE
Incorrect flag name "--use-python3"

### ISSUE THREAD

**Issue by derekwangHPEAruba** [StackStorm/st2docs#1008]
This page: https://docs.stackstorm.com/packs.html says to use the "--use-python3" flag, but that doesn't exist. The actual flag is called "--python3".

**Comment by armab** [comment]
@derekwangHPEAruba  Good catch! How about a PR to fix that?

Here is the original file: https://github.com/StackStorm/st2docs/blob/master/docs/source/packs.rst
