### ISSUE TITLE
HA doc needs an update RE: list of services relying on [coordination] backend

### ISSUE THREAD

**Issue by armab** [StackStorm/st2docs#1034]
A request from the https://github.com/StackStorm/st2-docker/pull/203#issuecomment-721390102 to double check and update the HA reference guide https://docs.stackstorm.com/reference/ha.html to include which services are relying on `[coordination]` backend.

@m4dcoder Looks like it became out of sync with time, for example `st2workflowengine` doesn't include coordination as a dependency. Is that the only one unsync service or there are more services which use coordination and it's not documented?

**Comment by m4dcoder** [comment]
Closed with https://github.com/StackStorm/st2docs/pull/1075
