### ISSUE TITLE
Global RBAC permissions needs to be documented

### ISSUE THREAD

**Issue by minsis** [StackStorm/st2docs#1083]
Carrying part of the conversion over from https://github.com/StackStorm/st2/issues/5303#issuecomment-892134776

The global RBAC permission types are not documented. While there is some overlap for types within some of the resources there should be a section specifying the global settings as well.

**Comment by armab** [comment]
Thanks for reporting this!

**Comment by amanda11** [comment]
In st2docs we generate the available_permission_types.rst by going through each resource and finding the permission types for each resource. But we don't go through the st2common.rbac.types.GLOBAL_PERMISSION_TYPES and generate that list.
Suggest amending generate-available-permission-types-table.py to generate the global list before it adds the resource lists. 
I can try and look at that if that sounds like a plan...
