### ISSUE TITLE
Centos 8 EOL

### ISSUE THREAD

**Issue by gardar** [StackStorm/st2docs#1104]
What's the plan now that Centos 8 is EOL?
Will AlmaLinux and/or RockyLinux be officially supported or will Centos Stream be supported?

Apologies if this is not the correct place to ask or if this has been discussed before, I didn't find any other topics on the subject.

**Comment by amanda11** [comment]
@gardar  Please see https://github.com/StackStorm/community/issues/88 where we are tracking the issue. The updates from the recent TSC meeting about this issue can be found at the bottom of that issue.

**Comment by gardar** [comment]
Ah there it is, was a bit surprised when I didn't find any discussions.
