### ISSUE TITLE
Documented instructions for RBAC role permissions are incorrect

### ISSUE THREAD

**Issue by satellite-no** [StackStorm/st2docs#1107]
Hi,

Maybe this is something I'm doing wrong but been playing with this for awhile and seems pretty straight forward but no matter what the permissions to an object are, none get applied only global level permissions work (action_list, execution_list, etc.)

The below is the commands I ran w/output and the st2.conf,  nothing is special about this its basiclly copy and paste from RBAC documentations. https://docs.stackstorm.com/rbac.html#using-rbac-example

[Command ran and output](https://pastebin.com/raw/QMKbJSrP)

[st2.conf](https://pastebin.com/raw/KDQWRZjx)

**Comment by amanda11** [comment]
This issue will now solely deal with the issue that the example in st2docs for RBAC is incorrect, and should be amended as per details above.
