### ISSUE TITLE
how to solve curl 60

### ISSUE THREAD

**Issue by PLPRASU** [StackStorm/st2docs#1122]
curl: (60) SSL certificate problem: self signed certificate
More details here: https://curl.haxx.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.

**Comment by cognifloyd** [comment]
This is not a help desk. If this is an issue with following StackStorm's docs, please post join our slack channel, and post a link to the part of the docs that has you stumped. Then ask your question. Thanks!
