### ISSUE TITLE
apt-get install st2 fails troubleshooting docs

### ISSUE THREAD

**Issue by lakshmi-kannan** [StackStorm/st2docs#180]
* One person tried to install st2 in i386 and he could never install. Packagecloud said this is apt specific. apt doesn't give appropriate error message. So let's note in docs.

* Another user complained about hash sum mismatch. This http://askubuntu.com/questions/41605/trouble-downloading-packages-list-due-to-a-hash-sum-mismatch-error fixed the issue for them. Manas also found http://blog.packagecloud.io/eng/2016/03/21/apt-hash-sum-mismatch/. 

We should add a troubleshooting doc here https://github.com/StackStorm/st2docs/tree/master/docs/source/troubleshooting

**Comment by LindsayHill** [comment]
We now have troubleshooting docs, and I submitted a patch a while back to crash out the install if user tries it on i386. It's also noted in the docs now.
