### ISSUE TITLE
References to gist.github.com

### ISSUE THREAD

**Issue by manasdk** [StackStorm/st2docs#201]
https://github.com/StackStorm/st2docs/blob/ed3fa0c113d1d0681c7e6e4a46cc91733bfa9dea/docs/source/reference/ha.rst contains references to https://gist.github.com/manasdk/fce14029900e533a385d. I don't plan to delete these anytime soon but perhaps a better idea to take over the content. Perhaps put it under a StackStorm owned and managed github users gist.

**Comment by m4dcoder** [comment]
https://github.com/StackStorm/st2docs/pull/204
