### ISSUE TITLE
Issue with, "st2 pack" commands through proxy

### ISSUE THREAD

**Issue by mchenetz** [StackStorm/st2docs#352]
I had issues initially getting the, `st2 pack` commands working with a proxy. I had followed the instructions from:
https://docs.stackstorm.com/reference/proxy.html?highlight=proxy

When i ran a, `st2 pack search monitoring` I got the following output:
`
400 Client Error: Bad Request
MESSAGE: No results from the index: tried https://index.stackstorm.org/v1/index.json.
Status: [
   {
       "url": "https://index.stackstorm.org/v1/index.json", 
       "message": "SSLError(SSLError(SSLError(\"bad handshake: SysCallError(104, 'ECONNRESET')\",),),)", 
       "error": "unresponsive", 
       "packs": 0
   }
] for url: http://127.0.0.1:9101/v1/packs/index/search`

# Fix
add: HTTP_PROXY and HTTPS_PROXY to the environment
`HTTP_PROXY=http://username:password@proxy:port/`
`HTTPS_PROXY=http://username:password@proxy:port/`
`no_proxy="127.0.0.1"`

### RUN:
`sudo st2ctl  restart`

## Might be needed - I made these changes too:
Modify: /opt/stackstorm/st2/lib/python2.7/site-packages/st2common/services/packs.py

### ADD:
`proxies = {
  'http': 'http://username:password@proxy:port',
  'https': 'http://username:password@proxy:port',
}'

### Modify
`request = requests.get(index_url)`
### To
`request = requests.get(index_url, proxies=proxies)`

### RUN:
`sudo st2ctl  restart`

**Comment by LindsayHill** [comment]
@sidkrishna could you take a look at this one when you get a chance? I'm not sure if the code changes are needed, or just the docs about setting environment variables.

**Comment by conor-owens** [comment]
I saw this issue too.  Centos7 and Stackstorm 2.1.0. More info: https://gist.github.com/conor-owens/21d2b291251c9f89ecef579de9fb5221

Seems the various environment variables are not preserved when running the packs.py so the requests doesn't find or use the HTTPS_PROXY environment variable.

**Comment by conor-owens** [comment]
I tried adding this to the packs.py to read the contents of /etc/environment:  
(ref: http://stackoverflow.com/questions/5971312/how-to-set-environment-variables-in-python)

`import re

LOG = logging.getLogger(__name__)

def _set_env_from_etc_environment(envFilePath):
    print('--packs.py:setEnvFromEnvFile --1-----------------------------------------------.')
    SetEnvPattern = re.compile("^(.*)(=)(.*)$", re.MULTILINE)
    SetEnvFile = open(envFilePath, "r")
    SetEnvText = SetEnvFile.read()
    SetEnvMatchList = re.findall(SetEnvPattern, SetEnvText)

    for SetEnvMatch in SetEnvMatchList:
        VarName=SetEnvMatch[0]
        VarValue=SetEnvMatch[2]
        print "-- %s=%s ------"%(VarName,VarValue)
        os.environ[VarName]=VarValue

_set_env_from_etc_environment("/etc/environment")`


This allows the packs index to be fetched so action packs.download now succeeds.

**Comment by conor-owens** [comment]
Also needed the sudo git config --global http.proxy http://proxy.somecorp.net:8080 for th egit clones

**Comment by Mierdin** [comment]
Please note https://github.com/StackStorm/st2docs/pull/388, that contains a more suitable workaround for ``st2 pack install`` that doesn't require any Python changes and also allows pack dependencies to install as well. Note also that it doesn't address ``st2 pack search`` at all, only pack installation.

I would like to keep this issue open, as we are going to be pursuing a more permanent solution to this problem in a future release.

**Comment by LindsayHill** [comment]
Closing this now that #3137 has been merged, and updated docs published
