### ISSUE TITLE
Repetition of steps to be corrected at https://docs.stackstorm.com/latest/install/deb.html#start-services

### ISSUE THREAD

**Issue by sidkrishna** [StackStorm/st2docs#364]
Steps for "Start Services" & "Register sensors, rules and actions" are listed twice in the doc. Should be needed only once.

**Comment by LindsayHill** [comment]
Looks like the rhel6 & rhel7 pages need tweaking too. Don't know how it ended up like that. You'd think we would have noticed it before.

**Comment by LindsayHill** [comment]
Fixed in #365
