### ISSUE TITLE
ST2 installation doc change to reduce confusion with Automation Suites

### ISSUE THREAD

**Issue by plaporte1** [StackStorm/st2docs#373]
At this location (https://bwc-docs.brocade.com/install/index.html) and after the sentence saying the “..install will take about 4 minutes..”, can we add a note to Automation Suite users who already have BWC installed? 

Insert this text:
NOTE: If you have already installed Workflow Composer and would like instructions for installing a Workflow Composer Automation Suite, use the Topics List on the left of the screen to locate and select your automation suite.

I uploaded a doc explaining in greater detail.

[BWC doc change request.docx](https://github.com/StackStorm/st2docs/files/739917/BWC.doc.change.request.docx)

**Comment by LindsayHill** [comment]
Thanks @plaporte1 

We'll need to figure out some of the mechanics around this. Ideally we only want that message displayed on bwc-docs.brocade.com, not on docs.stackstorm.com. 

Both sets of documentation are built from the same base, with BWC docs overlaid on the ST2 docs.

**Comment by LindsayHill** [comment]
Related: The main installation doc (/install/index.html) should be different for BWC vs ST2. The simple install option for ST2 should be replaced with the simple install for BWC on bwc-docs.brocade.com. Right now it's a little confusing.

**Comment by plaporte1** [comment]
Makes sense (mostly) since this is a BWC thing. Only concern is Network Essentials which, from what I understand, will work with ST2. Do we need to worry about that with ST2 users?

Patrick LaPorte
Director, Network Automation Marketing
Brocade
130 Holger Way, San Jose, CA 95134
T . +1.408.333.4124     M. +1.408.425-3373
www.brocade.com<http://www.brocade.com/>
[http://connect.brocade.com/archives/mktgcorporatemarketing/Marketing%20Communications/Documents/E-mail%20signature%20banners/email-sig-general-new-ip.png]

**Comment by LindsayHill** [comment]
Network Essentials will probably stay in the BWC docs, but we'll link to those from the ST2 docs. All docs are public, so should be no problems there.

**Comment by LindsayHill** [comment]
Not going to implement this as-is. Will restructure EWC docs differently.
