### ISSUE TITLE
CentOS installation notes should include firewall rule requirements

### ISSUE THREAD

**Issue by LindsayHill** [StackStorm/st2docs#383]
If a user installs a new CentOS 7.x system from installation ISO, by default the local firewall will block all non-SSH traffic.

This is confusing for users who do not have the Linux experience to diagnose & remediate firewall configurations. We do not want to automatically reconfigure the user's firewall settings, but we should help them resolve it, by providing the commands they can run to resolve it.

Our documentation for installing ST2 on CentOS 7.x should include info about running these commands to add rules to allow HTTP & HTTPS traffic, and to make those changes survive reboot:
```
firewall-cmd --zone=public  --add-service=http --add-service=https
firewall-cmd --zone=public --permanent --add-service=http --add-service=https
```

We probably also need to update the main install page with a reference to these firewall rule changes. 

NB: If you use Vagrant and the `centos/7` box, it does not have this issue. `firewalld` is installed, but is disabled by default. This is only an issue if you are installing from the CentOS ISO.

**Comment by Kami** [comment]
Yeah, I think that's a good idea.

IIRC, at some point in the past, we totally disabled the firewall inside the installer script (which is obviously not a good idea :)).
