### ISSUE TITLE
Explicitly mention in st2docs owner:group when deploying config file manually

### ISSUE THREAD

**Issue by sidkrishna** [StackStorm/st2docs#445]
Pack config files at /opt/stackstorm/configs/<pack>.yaml when created manually should be given owner:group = st2:root. Docs can be updated to state this for cases when user does not use `st2 pack config <pack>` for configuring pack. 

Related to: https://github.com/StackStorm/ops-infra/pull/126#discussion_r109145971

**Comment by LindsayHill** [comment]
Will be addressed in #507 when merged
