### ISSUE TITLE
Need to restart chatops to delete duplicate aliases

### ISSUE THREAD

**Issue by Mierdin** [StackStorm/st2docs#457]
A user [was noticing duplicate chatops aliases](https://stackstorm-community.slack.com/archives/C066APT88/p1491333849029639) when they made changes to them - apparently `st2chatops` caches each iteration of these. 

Turns out, restarting `st2chatops` reloads these from the filesystem, so we should add a note to the docs that highlights this.

Maybe consider adding here: https://docs.stackstorm.com/chatops/aliases.html#removing

**Comment by estee-tew** [comment]
https://stackstorm.slack.com/archives/community/p1491334304217764
