### ISSUE TITLE
Sensor documentation should be improved to have real working sensors

### ISSUE THREAD

**Issue by lakshmi-kannan** [StackStorm/st2docs#470]
jeremybr on slack:

https://docs.stackstorm.com/sensors.html#creating-a-sensor shows a blank class as the sample sensor impl. I can just look in the installed packs but I would fix this. the SamplePollingSensor is blank too.

**Comment by jeremyjjbrown** [comment]
Also, https://docs.stackstorm.com/sensors.html#sensor-service says

> As you can see in the example above, a sensor_service is passed to each sensor class constructor on instantiation

But this is not in the either example on the page.

.
