### ISSUE TITLE
https://docs.stackstorm.com/mistral.html# mentions a '--tasks' option to 'st2 execution get' but that option doesn't exist.

### ISSUE THREAD

**Issue by mbrannigan** [StackStorm/st2docs#484]
The documentation says:
To display subtasks, run `st2 execution get <execution-id> --tasks`

It looks like the default for `st2 execution get` displays all subtasks by default?

**Comment by LindsayHill** [comment]
Looks like this was changed at v1.3.0 (https://docs.stackstorm.com/changelog.html#january-22-2016)

> The `--tasks` option in the CLI for `st2 execution get` and `st2 run` will be renamed to `--show-tasks` to avoid conflict with the tasks option in `st2 execution re-run`.

Addressed in #515
