### ISSUE TITLE
Clarify datastore requirements

### ISSUE THREAD

**Issue by cognifloyd** [StackStorm/st2docs#510]
It seems that the datastore requires that all values be strings. Since it is backed by mongo, I figured it would be happy to store json objects as well. It feels funny to do a json.dumps to store a json object as a string in what is ultimately backed by a json-native document store.

Maybe clarify in the docs about what data types are allowed for datastore values, and hopefully explain why those requirements are there.

**Comment by Mierdin** [comment]
👍 , and for future readers, it looks like this is enforced by the JSON schema embedded in the KeyValue API models https://github.com/StackStorm/st2/blob/master/st2common/st2common/models/api/keyvalue.py#L61

**Comment by cognifloyd** [comment]
I just found this docs reference that describes why the datastore is limited to strings. This needs to be linked to from the datastore doc/section at least.
https://docs.stackstorm.com/latest/reference/pack_configs.html#dynamic-config-values

> **Dynamic config values**
> Right now only string type is supported for dynamic config values (config items who’s value is retrieved from the datastore). This was done intentionally to keep the feature simple and fully compatible with the existing datastore operations (this means you can re-use the same API, CLI commands, etc.).
> 
> To work-around this (in case you want to use a non-string value) you can, for example, store a JSON serialized version of the your value in the datastore and then de-serialize it in the action / sensor code.
> 
> If this turns out to be a big problem for many users, we might consider introducing support for arbitrary types, but this would most likely mean we will need to implement a new API and CLI commands for managing dynamic config values and that’s something we want to avoid.
>
