### ISSUE TITLE
RBAC - No reference to enable in st2.conf

### ISSUE THREAD

**Issue by bigmstone** [StackStorm/st2docs#575]
RBAC docs do not make note of enabling in `st2.conf` with the following configuration:

```
[rbac]
enable = True
```

**Comment by LindsayHill** [comment]
This gets automatically done by the installation script if BWC is installed via the one-liner. It does not get done by the packaging.

So docs updates need to include this as a note for manual installs.

Additionally, they should include note about needing to create assignment for `stanley`. This gets done automatically with install script, but not by packaging. Docs say that stanley automatically gets admin role, but this is no longer correct
