### ISSUE TITLE
Unclear note about format ordering for action aliases

### ISSUE THREAD

**Issue by vincent-legoll** [StackStorm/st2docs#586]
in https://docs.stackstorm.com/chatops/aliases.html#multiple-formats-in-single-alias
there's a note explaining that formats should be listed in "specific" before "generic" order.

But this looks contradictory to the example just above:
```
formats:
    - "list sensors"
    - "list sensors from {{ pack }}"
```
This looks backwards wrt ordering...

I see two possible solutions:
- make the note use the example code (`list sensors`, etc...), and not something else (`deploy ...`) so that they are both refering and showing the same thing.
- Explain in which way the example above the note differs from what the note is about.

**Comment by LindsayHill** [comment]
You're quite right, this is confusing. I will do some tests to confirm behavior, and update the docs.

**Comment by LindsayHill** [comment]
I've been looking at this a bit more. The note is a different situation to that shown in the example. In the example, we have
```yaml
    - "list sensors"
    - "list sensors from {{ pack }}"
    - "sensors list"
```

Note that there is only one variable match there, and AFAICT, we don't need to change the ordering. In the note paragraph, the YAML would look like this:

```yaml
    - "deploy {{ pack }} to {{ host }}"
    - "deploy {{ pack }}"
```

I'll see if I can reword that to make it more obvious that it is a different scenario

**Comment by vincent-legoll** [comment]
I don't understand what you're saying. 

If you're counting parameters, then zero param looks more generic than one param.

It looks like you're trying to say that zero param is a special case that does not have ordering constraints wrt multiple params.

And for those with multiple params, they should be ordered by decreasing number of params.

**Comment by LindsayHill** [comment]
Have just heard that ordering may not matter anyway, after some other code changes. Testing needed...

**Comment by LindsayHill** [comment]
I just did some testing for this. Doesn't look like ordering matters any more.
