### ISSUE TITLE
Document uninstall procedure

### ISSUE THREAD

**Issue by LindsayHill** [StackStorm/st2docs#615]
We should document the uninstallation procedure for StackStorm. Basically the reverse of the manual install procedures.

Ideally this will be scripted later.

**Comment by leoxhj** [comment]
Is possible to degrade from a specific version? for example, we upgrade from 2.3.2 to 2.4.1, but we found 2.4.1 has some significant issues, then we want degrade to 2.3.2.

**Comment by LindsayHill** [comment]
If you're using the install script, you can tell it to install a specific version by passing in `--version=2.3.2`.

If you're manually installing Debs, you can specify the package versions with something like this:
`sudo apt-get install st2=2.3.2-7 st2mistral=2.3.2-6`.
Use `sudo apt-cache policy st2` to see what specific package versions are available.

For RHEL systems, use `sudo repoquery --nvr --show-duplicates st2` to find available package versions, and install specific versions with `sudo yum install st2-2.3.2-7`.

If you're trying to do this on an existing system, you may need to uninstall ST2 packages first.

There are no guarantees that this will work. We don't test downgrades. That is why we recommend doing a backup prior to upgrading. If you need to change version, we would recommend restoring from backup, or installing the older version of ST2 on a new system, and migrate your content across.

**Comment by LindsayHill** [comment]
Uninstall docs in #671
