### ISSUE TITLE
Document how to set kv store item TTL

### ISSUE THREAD

**Issue by vincent-legoll** [StackStorm/st2docs#627]
In the doc:
https://docs.stackstorm.com/datastore.html#setting-a-key-value-pair-ttl
we see that we can set TTL on key/value store items.

I'm looking for a way to do that in python.

But even searching the REST API docs I couldn't find a reference to TTL setting, what am I missing ?

It looks like I can do:
```
from st2client.client import Client
from st2client.models import KeyValuePair
a=KeyValuePair(name='toto', value='titi', ttl=34)
cnx = Client(base_url='http://localhost')
cnx.keys.update(a)
```

Which seems to be working...

Edit: I can prepare a small PR to add that to the existing examples, if this is the way to go...

**Comment by LindsayHill** [comment]
This PR should address the missing REST API reference: https://github.com/StackStorm/st2/pull/3787

Happy to accept a PR to update examples here too
