### ISSUE TITLE
Should we localize modernizr.js?

### ISSUE THREAD

**Issue by LindsayHill** [StackStorm/st2docs#649]
Should we do something similar to https://github.com/rtfd/sphinx_rtd_theme/pull/143/commits/e374f68b4789f694ff6b5ad4ca3c77b33a019a3b, and distribute a local JS copy, rather than an external CDN-hosted version? Will work better for those users in air-gapped environments.

Similar question for fonts.

Thoughts @enykeev? To me it seems to be simple enough, and probably doesn't make too much difference if we change to a local version. But I might be missing something

**Comment by enykeev** [comment]
No, you are correct, the effects of using cdn version are pretty negligible. Frankly, I'm not sure we even need modernizer at all this days, but getting rid of it would be little bit more involving.

**Comment by LindsayHill** [comment]
Thanks for input. Having thought about it some more, I think I'll probably leave it alone for now, and look at it as part of a bigger theme overhaul in future.
