### ISSUE TITLE
/etc/nginx/conf.d/st2.conf server_name directive

### ISSUE THREAD

**Issue by soloman747** [StackStorm/st2docs#680]
In the /etc/nginx/conf.d/st2.conf file, the file doesn't include a server_name directive. Without including this directive, regular ssl certificates will work, but wildcard certificates will not. The only indication of a problem will be that when you log into the site, you will receive notice of an insecure certificate issue. You should probably add this note to the documentation at:

https://docs.stackstorm.com/install/deb.html#install-webui-and-setup-ssl-termination

**Comment by armab** [comment]
We're using wildcard cert and it works with the original shipped nginx `st2.conf` with no issues.

I guess the wildcard & default_server in
```
server {
  listen *:80 default_server;

server {
  listen       *:443 ssl;
```
covers that as a catch-all.

Also nginx version might be important here, here is ours:
```
nginx -v
nginx version: nginx/1.12.2
```

**Comment by soloman747** [comment]
We have the same version, and we are using the default azure repositories on Ubuntu 16.04.3 LTS. We don't have any load-balancers or proxies. Are you sure you haven't added entries in your hosts file or anything?

nginx -v
nginx version: nginx/1.12.2

Ubuntu 16.04.3 LTS (GNU/Linux 4.11.0-1016-azure x86_64)

This is our st2.conf file config, (removing, of course, the actual domain name in the server_name directive:

`
server {
  listen *:80 default_server;

  add_header Front-End-Https on;
  add_header X-Content-Type-Options nosniff;

  if ($ssl_protocol = "") {
       return 301 https://$host$request_uri;
  }

  index  index.html;

  access_log /var/log/nginx/st2webui.access.log combined;
  error_log /var/log/nginx/st2webui.error.log;
}

server {
  listen       *:443 ssl;

  ssl on;

  ssl_certificate           /etc/ssl/st2/st2.crt;
  ssl_certificate_key       /etc/ssl/st2/st2.key;
  ssl_session_cache         shared:SSL:10m;
  ssl_session_timeout       5m;
  ssl_protocols             TLSv1 TLSv1.1 TLSv1.2;
  ssl_ciphers               EECDH+AESGCM:EDH+AESGCM:AES256+EECDH:AES256+EDH:ECDHE-RSA-AES128-GCM-SHA384:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA128:DHE-RSA-AES128-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES128-GCM-SHA128:ECDHE-RSA-AES128-SHA384:ECDHE-RSA-AES128-SHA128:ECDHE-RSA-AES128-SHA:ECDHE-RSA-AES128-SHA:DHE-RSA-AES128-SHA128:DHE-RSA-AES128-SHA128:DHE-RSA-AES128-SHA:DHE-RSA-AES128-SHA:AES128-GCM-SHA384:AES128-GCM-SHA128:AES128-SHA128:AES128-SHA128:AES128-SHA:AES128-SHA:HIGH:!aNULL:!eNULL:!EXPORT:!DES:!MD5:!PSK:!RC4;
  ssl_prefer_server_ciphers on;


  index  index.html;
  server_name           x.x.x.com;
  access_log            /var/log/nginx/ssl-st2webui.access.log combined;
  error_log             /var/log/nginx/ssl-st2webui.error.log;

  add_header              Front-End-Https on;
  add_header              X-Content-Type-Options nosniff;

  location @apiError {
    add_header Content-Type application/json always;
    return 503 '{ "faultstring": "Nginx is unable to reach st2api. Make sure service is running." }';
  }

  location /api/ {
    error_page 502 = @apiError;
`

**Comment by armab** [comment]
What's the diff when you're trying to access `curl -vL https://your.wildcard.host` with or without nginx `server_name` configured? I guess you don't have any other websites in your nginx configured.


You also said: 
> The only indication of a problem will be that when you log into the site, you will receive notice of an insecure certificate issue. 

Do you mean here you're getting an error after logging-in into `st2web` or just navigating to website URL? Please write out exactly what errors you're getting.

Quick example when I'm accessing website by a wrong URI/domain name, say `ubuntu16`: 
```
ubuntu16 uses an invalid security certificate. The certificate is only valid for the following names: *.uswest2.stackstorm.net, uswest2.stackstorm.net Error code: SSL_ERROR_BAD_CERT_DOMAIN
```
Obviously in this case if I navigate it via test1.uswest2.stackstorm.net it shows no error and so some DNS should reflect that to direct me to the correct IP (exactly that server).
Since you also mentioned hosts modifications, is that different with configured `server_name`, does it perform additional redirect for you?

**Comment by soloman747** [comment]
It seems I can no longer reproduce the problem. I've commented out the server_name directive and it appears to still say the certificate is secure. 

To answer your questions, this is a brand new server running on an Azure VM. The only thing that has been installed on this machine is the st2 software. No other custom configurations have been performed, as this is strictly an st2 server.

I have a wildcard certificate from godaddy.com. I first requested that the subdomain be added as a cname record with my godaddy domain registrar. I then chained the wildcard certificate and the godaddy intermediate certificate into a chained certificate using the "cat wildcard.crt intermediate.crt > chained.crt" syntax. I used that certificate, along with the corresponding certificate key for the "ssl_certificate" and "ssl_certificate_key" values in the /etc/nginx/conf.d/st2.conf file, and restarted nginx. Please note that I didn't modify my hosts file in the least. The only entry in my hosts file was for my loopback address. 

When browsing to the site, the web browser indicated that I had an insecure certificate. I went back into the /etc/nginx/conf.d/st2.conf file, added the server_name directive with the subdomain, and restarted nginx. The site came up showing that my connection was now secure, with a valid certificate. 

I'm not sure why I cannot reproduce the problem at this time, but hopefully these steps can serve as a workaround for anybody else experiencing a similar problem.

**Comment by armab** [comment]
Good to hear it works :+1:
