### ISSUE TITLE
Rule examples for webhooks reference trigger.payload

### ISSUE THREAD

**Issue by lampwins** [StackStorm/st2docs#681]
The examples for rules which reference webhook triggers, use `trigger.payload` which I have never found to be correct (I always have to remove `payload`). It would be nice to either clean this up or talk about such a case in which `payload` is needed.

**Comment by LindsayHill** [comment]
Thanks for that - I've been vaguely aware that there are some inconsistencies, but I've never tracked down exactly what it should be

**Comment by LindsayHill** [comment]
I've got a feeling the inconsistency might be related to using the generic webhook trigger vs core.st2.webhook trigger.

Needs a bit more testing to confirm behavior

**Comment by lampwins** [comment]
On that note, I have always used `core.st2.webhook`

**Comment by LindsayHill** [comment]
Have just been reviewing this, and doesn't look like there's any `trigger.payload` examples in Rules docs anymore. Looks like it's `trigger.payload_parameter_1`-type things. So this might have been cleaned up at some point. If you find any specific references that need updating, let me know.
