### ISSUE TITLE
When I use webhook, how do i to get execution ID?

### ISSUE THREAD

**Issue by fengbao123** [StackStorm/st2docs#697]
> Webhooks simply submit data into StackStorm. So if you want data back from StackStorm, or an action execution ID, **you’ll have to get that data in an asynchronous fashion.**

When I call webhook, how do i to get this execution ID? Tks!

**Comment by LindsayHill** [comment]
Webhooks do not guarantee that a single task will get executed. It could be zero, one or more actions that get spawned in response to a webhook. 

If you specifically want to execute an action, you may be better off using the executions API. See https://docs.stackstorm.com/webhooks.html#when-not-to-use-webhooks

**Comment by fengbao123** [comment]
thank you very much
