### ISSUE TITLE
Update Architecture Diagram

### ISSUE THREAD

**Issue by nmaludy** [StackStorm/st2docs#806]
In the architectural diagrams:
- https://docs.stackstorm.com/install/overview.html
- https://docs.stackstorm.com/reference/ha.html

The picture does not take into account two new architectural changes:
- `mistral` now uses callbacks, so it communicates back to `st2api`
- `st2workflowengine` now exists and is a service that communicates with `rabbitmq` and `mongodb` (i believe)

**Comment by LindsayHill** [comment]
Think this is closed by https://github.com/StackStorm/st2docs/pull/894
