### ISSUE TITLE
StackStorm architecture images are missing new services

### ISSUE THREAD

**Issue by nmaludy** [StackStorm/st2docs#858]
The StackStorm architecture images:
- https://github.com/StackStorm/st2docs/blob/master/docs/source/_static/images/st2-deployment-big-picture.png
- https://github.com/StackStorm/st2docs/blob/master/docs/source/_static/images/st2-deployment-multi-node.png

Need to be updated to include the new services:
- st2scheduler
- st2timerengine
- st2workflowengine

Additionally the following page is missing documentation for those new services: https://docs.stackstorm.com/install/overview.html

**Comment by LindsayHill** [comment]
Closed by https://github.com/StackStorm/st2docs/pull/894
