### ISSUE TITLE
Add "st2" database name to the database connection string

### ISSUE THREAD

**Issue by RaviTezu** [StackStorm/st2docs#935]
Doc says the database connection string can be: 
```
[database]
host = mongodb://<#MDB_NODE_1>,<#MDB_NODE_2>,<#MDB_NODE_3>/?replicaSet=<#MDB_REPLICA_SET_NAME
```

But I think, it will be helpful if we can add the database name(`st2`) to it. 
In short, it should be: 
```
[database]
host = mongodb://<#MDB_NODE_1>,<#MDB_NODE_2>,<#MDB_NODE_3>/st2?replicaSet=<#MDB_REPLICA_SET_NAME
```
File/Line to change: 
https://github.com/StackStorm/st2docs/blame/2b520141ae02e66711bdb3d8965425e08e2d8162/docs/source/install/config/config.rst#L43

**Comment by nmaludy** [comment]
@RaviTezu feel free to open a PR against this repo!

Once it gets merged it will deploy out into the live docs.

**Comment by RaviTezu** [comment]
The mongo doc has the required info. Closing this.
