### ISSUE TITLE
Error in installing st2

### ISSUE THREAD

**Issue by adyanthaya17** [StackStorm/st2docs#959]
Hi,

I am facing an issue when it comes to installing the st2 while following the document https://translate.googleusercontent.com/translate_c?depth=1&hl=en&prev=search&rurl=translate.google.com&sl=ja&sp=nmt4&u=https://docs.stackstorm.com/latest/install/rhel7.html&xid=17259,15700021,15700186,15700191,15700256,15700259,15700262,15700265,15700271&usg=ALkJrhh8DlIQFeTnnxU-mwpUFDySy84Y3A#system-requirements

The error looks like this: 

Errors:
No results from the index: tried https://index.stackstorm.org/v1/index.json.
Status: [
    {
        "url": "https://index.stackstorm.org/v1/index.json",
        "message": "SSLError(MaxRetryError('HTTPSConnectionPool(host=\\'index.stackstorm.org\\', port=443): Max retries exceeded with url: /v1/index.json (Caused by SSLError(SSLError(\"bad handshake: SysCallError(104, \\'ECONNRESET\\')\",),))',),)",
        "error": "unresponsive",
        "packs": 0
    }
]
"
  stdout: ''
error: No handlers could be found for logger "st2.st2common.services.packs"
Traceback (most recent call last):
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/python_runner/python_action_wrapper.py", line 333, in <module>
    obj.run()
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/python_runner/python_action_wrapper.py", line 192, in run
    output = action.run(**self._parameters)
  File "/opt/stackstorm/packs/packs/actions/pack_mgmt/download.py", line 78, in run
    return self._validate_result(result=result, repo_url=pack_url)
  File "/opt/stackstorm/packs/packs/actions/pack_mgmt/download.py", line 99, in _validate_result
    raise Exception(message)
Exception: The pack has not been downloaded from "None".

Errors:
No results from the index: tried https://index.stackstorm.org/v1/index.json.
Status: [
    {
        "url": "https://index.stackstorm.org/v1/index.json",
        "message": "SSLError(MaxRetryError('HTTPSConnectionPool(host=\'index.stackstorm.org\', port=443): Max retries exceeded with url: /v1/index.json (Caused by SSLError(SSLError("bad handshake: SysCallError(104, \'ECONNRESET\')",),))',),)",
        "error": "unresponsive",
        "packs": 0
    }
]

traceback: None
failed_on: download pack
start_timestamp: Wed, 22 Jan 2020 05:11:55 UTC
end_timestamp: Wed, 22 Jan 2020 05:11:58 UTC
+--------------------------+---------------------+---------------+----------------+-------------------------------+
| id                       | status              | task          | action         | start_timestamp               |
+--------------------------+---------------------+---------------+----------------+-------------------------------+
| 5e27d99b9d63510d3d25b7a6 | failed (2s elapsed) | download pack | packs.download | Wed, 22 Jan 2020 05:11:55 UTC |
+--------------------------+---------------------+---------------+----------------+-------------------------------+

**Comment by blag** [comment]
From [the installation documentation](https://docs.stackstorm.com/3.1/install/index.html?highlight=firewall#ref-one-line-install):

> If you’re installing behind a proxy, just export the proxy ENV variables http_proxy, https_proxy, no_proxy before running the script.
> 
> export http_proxy=http://proxy.server.io:port
> export https_proxy=http://proxy.server.io:port
> export no_proxy=localhost,127.0.0.1
> 
> In case of MITM proxy, you may need to export additional proxy_ca_bundle_path, see Installing Packs from Behind a Proxy.
> 
> If you have problems accessing the Web UI on a RHEL 7/CentOS 7 system, check the system firewall settings.

**Comment by adyanthaya17** [comment]
I did export the proxy details as mentioned above but the error still persists.

**Comment by winem** [comment]
Does a simple curl or wget to https://index.stackstorm.org/v1/index.json work via the proxy?

**Comment by adyanthaya17** [comment]
It doesn't work. This is the output recieved: 

[root@stack ~]# wget https://index.stackstorm.org/v1/index.json
--2020-01-23 10:57:54--  https://index.stackstorm.org/v1/index.json
Resolving index.stackstorm.org (index.stackstorm.org)... 104.18.37.18, 104.18.36.18, 2606:4700:3035::6812:2412, ...
Connecting to index.stackstorm.org (index.stackstorm.org)|104.18.37.18|:443... connected.
Unable to establish SSL connection.

**Comment by winem** [comment]
So this seems to be an issue with the Proxy and not an issue with stackstorm.org. 

Do you have access to the access- and error logs of the proxy? This is where the investigation and troubleshooting should continue.

**Comment by armab** [comment]
Thanks @winem for helping.

@adyanthaya17 This indeed looks like proxy configuration issue and not StackStorm issue.
For asking questions or getting debugging help from Community, please use our Slack or Forum, while Github repositories are for reporting bugs or contributions.
