### ISSUE TITLE
EWC references in the docs

### ISSUE THREAD

**Issue by timfong888** [StackStorm/st2docs#985]
I checked with Linux Foundation legal counsel today regarding content referring to a commercial product within the docs.  There are a few others I've seen similar to the following:

https://github.com/StackStorm/st2docs/blob/master/docs/source/install/ewc.rst

He suggested it might've been an oversight, but could I get some additional coloring on it?

**Comment by armab** [comment]
There were also Enterprise product descriptions and page on the main https://stackstorm.com/ website, but that was removed around 2019 once the StackStorm migration to the Linux Foundation was announced.

Yes, with the StackStorm Enterprise Open Source now https://stackstorm.com/2020/05/27/extreme-networks-donates-ewc-to-linux-foundation/ we'll need to re-work all the docs.

**Comment by armab** [comment]
I just added this task into the new [EWC OpenSource Migration](https://github.com/orgs/StackStorm/projects/14) project.

**Comment by amanda11** [comment]
@armab This issue ws moved to done in the StackStorm v3.3.0 project, but that doesn't seem to have affected it's state in the EWC Migration project. Is it ok to move it to Done in this project too?

**Comment by armab** [comment]
While the links to EWC were removed it still looks after the first iteration we'll need another follow-up on the docs once we'll integrate LDAP and RBAC into st2 open source in full.

Quick search highlights items we'll need to to refactor after integrating those features:
- https://docs.stackstorm.com/latest/authentication.html?highlight=enterprise#ldap-enterprise-edition
- https://docs.stackstorm.com/latest/inquiries.html?highlight=enterprise
- https://docs.stackstorm.com/latest/install/overview.html?highlight=enterprise
- https://docs.stackstorm.com/latest/install/k8s_ha.html#enterprise-ewc
- https://docs.stackstorm.com/latest/install/ansible.html#ewc

and so we could remove `ewc` and `enterprise` keywords completely.

**Comment by blag** [comment]
Status update:

## Done ##

- [x] https://docs.stackstorm.com/latest/authentication.html?highlight=enterprise#ldap-enterprise-edition
- [x] https://docs.stackstorm.com/latest/install/ansible.html#ewc
- [x] more https://docs.stackstorm.com/latest/search.html?q=enterprise&check_keywords=yes&area=default
- [x] more https://docs.stackstorm.com/latest/search.html?q=ewc&check_keywords=yes&area=default

## Still To Do ##

- [ ] https://docs.stackstorm.com/latest/inquiries.html?highlight=enterprise
- [ ] https://docs.stackstorm.com/latest/install/overview.html?highlight=enterprise
- [ ] https://docs.stackstorm.com/latest/install/k8s_ha.html#enterprise-ewc
